### ISSUE TITLE
Logo proposal: Eve

### ISSUE THREAD

**Issue by baranpirincal** [biezhi/dev-fun#1]
Hello! I can contribute on your project with making a logo design. What do you think about it? If you have an idea we can talk together and create a suitable logo design for Eve. I'm waiting your feedback, Have a nice day! :smile: 

Best Regards,
Baran Pirincal
Visual Communication Designer

**Comment by hellokaton** [comment]
Wow, that's great. I'm really happy to get a nice logo, and `eve` means to explore new things every day.
If you want to design a logo, I want to use these three letters, and maybe you will have a cool idea.

**Comment by baranpirincal** [comment]
Hey again, I made a meaningful logo design, also its include "eve" but not directly. I'm waiting your feedbacks. If you liked the idea we can try it with different colors. I put inspirations of my idea below the logo design. I wanted to show "explore". However, if you don't like I can try again. Good evening!

![456456](https://user-images.githubusercontent.com/37786733/39279973-09ee0692-4905-11e8-9114-14644bf8bb2a.jpg)

**Comment by hellokaton** [comment]
@baranpirincal Very good, black if you can change a color. The two sets of logos were meant to show the `green` and `white` "eve", and I observed it, because the black was so conspicuous. logo below the inspiration resources is round, in the logo is clear, what does the design have? 

Thank you for your efforts. I am not an expert in this field. I have made some comments.😛

**Comment by baranpirincal** [comment]
@biezhi Thanks a lot for your valuable comments. Firstly, I want to say that you have not to be an expert to criticize a proposed logo design, especially on your project. Of course you know best the logo design is suitable or not with your project or is it reflecting the function/meaning/purposes of the project.

If I talk about design decisions, firstly I didn’t want to show “eve” words directly. I think our most important keyword is “discovering”, because of that I did not want people to understand “eve” letters on the logo design at first sight. I am sure that when people see the description of the project or when they start to use and understand the function of the project they will “discover” our logo design and they definitely like it. 

I put below the resources of inspirations just for showing my idea. I want to show form of binoculars and glasses which are related with “discovering” on logo design.

Forms of “e” letters are same and round,
Form of “v” letter is flat, because if we make it round or soft, it may look like “U” letter. Also the “v” letter is connecting with “e” letters as in the binoculars and glasses. But if you want me to make softer, definitely I can try it.

Lastly, I want to ask, what colors you prefer on logo design and if there is any place you wanted to change please tell me, I will work on that as soon as possible.

Have a nice day! :smile:

**Comment by baranpirincal** [comment]
@biezhi I'm waiting your feedback! :)

**Comment by hellokaton** [comment]
@baranpirincal I'm sorry for replying you late. I like orange or red. Would you like to see your plan?

**Comment by baranpirincal** [comment]
@biezhi I will put here orange and red versions of logo design asap.

**Comment by baranpirincal** [comment]
@biezhi 

![eve](https://user-images.githubusercontent.com/37786733/39576508-01d4431c-4ee7-11e8-81b2-f5617084f619.jpg)

**Comment by hellokaton** [comment]
I like this red one, it's already on the [README](https://github.com/biezhi/eve/blob/master/README.md), thanks for your pay.

`2` and `6` are also great colors and look forward to receiving their svg version.

**Comment by baranpirincal** [comment]
@biezhi I uploaded 2 and 6 under the name of alternative colors, good luck with that!
